name: my First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "my First github workflow"
            
            - name: checkout
              uses: actions/checkout@v6

            - name: List and read files
              run: |
                echo "my first github action job"
                ls -ltra
                cat README.md


            - name: Genrate ASCII Artwork
              run: cowsay -f dragon "Run for cover, Iam a DRAGON..RAWR" >> dragon.txt


