name: Exploring Variable and secrets

on:
    push

# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build
#               run: docker build -t docker.io/dockerUsername/imageName:latest

#             - name: docker login
#               run: docker login --username=dockerUsername --password=Luckey@123

#             - name: Docker Publish
#               run: docker push docker.io/dockerUsername/imageName:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#           - name: Docker Run
#             run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest


##########################################env-at-step-level#################################


# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: yewaleajay
#                 IMAGE_NAME: nginx
#               run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#             - name: docker login
#               env:
#                 DOCKER_USERNAME: yewaleajay
#                 DOCKER_PASSWORD: Luckey@123
#               run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#             - name: Docker Publish
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: yewaleajay
#                 IMAGE_NAME: nginx
#               run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#           - name: Docker Run
#             env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: yewaleajay
#                 IMAGE_NAME: nginx
#             run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

##########################################env-at-job-level#################################

# jobs:
#     docker:
#         env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: yewaleajay
#             IMAGE_NAME: nginx
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build
              
#               run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#             - name: docker login
#               env:
#                 DOCKER_PASSWORD: Luckey@123
#               run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#             - name: Docker Publish
#               env:
#                 IMAGE_NAME: nginx
#               run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#     deploy:
#         env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: yewaleajay
#             IMAGE_NAME: nginx
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#           - name: Docker Run
#             run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

##########################################env-at-workflow-level#################################
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: yewaleajay
    IMAGE_NAME: nginx

jobs:
    docker:
        
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build   
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: docker login
              env:
                DOCKER_PASSWORD: Luckey@123
              run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: Docker Publish
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

